# Generated by Django 2.2.6 on 2019-12-03 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedShifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='year')),
                ('month', models.IntegerField(verbose_name='month')),
                ('day', models.IntegerField(verbose_name='day')),
                ('is_absence', models.BooleanField(default=False, verbose_name='is_absence')),
                ('since', models.IntegerField(default=9, verbose_name='since')),
                ('to', models.IntegerField(default=22, verbose_name='to')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Members', verbose_name='member')),
            ],
            options={
                'db_table': 'requested_shifts',
                'unique_together': {('member', 'year', 'month', 'day')},
            },
        ),
    ]
