# Generated by Django 2.2.6 on 2019-12-03 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalPersonalShifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.IntegerField(verbose_name='since')),
                ('to', models.IntegerField(verbose_name='to')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Members', verbose_name='member')),
            ],
            options={
                'db_table': 'final_personal_shifts',
            },
        ),
        migrations.CreateModel(
            name='FinalSmgShifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('close_shifts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='close_shifts', to='create.FinalPersonalShifts', verbose_name='close_shifts')),
                ('open_shifts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_shifts', to='create.FinalPersonalShifts', verbose_name='open_shifts')),
            ],
            options={
                'db_table': 'final_smg_shifts',
            },
        ),
        migrations.CreateModel(
            name='FinalKitchenShifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('am1_shifts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_am1_shifts', to='create.FinalPersonalShifts', verbose_name='am1_shifts')),
                ('am2_shifts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_am2_shifts', to='create.FinalPersonalShifts', verbose_name='am2_shifts')),
                ('am3_shifts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_am3_shifts', to='create.FinalPersonalShifts', verbose_name='am3_shifts')),
                ('am4_shifts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_am4_shifts', to='create.FinalPersonalShifts', verbose_name='am4_shifts')),
                ('pm1_shifts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_pm1_shifts', to='create.FinalPersonalShifts', verbose_name='pm1_shifts')),
                ('pm2_shifts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_pm2_shifts', to='create.FinalPersonalShifts', verbose_name='pm2_shifts')),
                ('pm3_shifts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_pm3_shifts', to='create.FinalPersonalShifts', verbose_name='pm3_shifts')),
                ('pm4_shifts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_pm4_shifts', to='create.FinalPersonalShifts', verbose_name='pm4_shifts')),
            ],
            options={
                'db_table': 'final_kitchen_shifts',
            },
        ),
        migrations.CreateModel(
            name='FinalCounterShifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('am1_shifts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_am1_shifts', to='create.FinalPersonalShifts', verbose_name='am1_shifts')),
                ('am2_shifts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_am2_shifts', to='create.FinalPersonalShifts', verbose_name='am2_shifts')),
                ('am3_shifts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_am3_shifts', to='create.FinalPersonalShifts', verbose_name='am3_shifts')),
                ('am4_shifts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_am4_shifts', to='create.FinalPersonalShifts', verbose_name='am4_shifts')),
                ('am5_shifts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_am5_shifts', to='create.FinalPersonalShifts', verbose_name='am5_shifts')),
                ('pm1_shifts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_pm1_shifts', to='create.FinalPersonalShifts', verbose_name='pm1_shifts')),
                ('pm2_shifts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_pm2_shifts', to='create.FinalPersonalShifts', verbose_name='pm2_shifts')),
                ('pm3_shifts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_pm3_shifts', to='create.FinalPersonalShifts', verbose_name='pm3_shifts')),
                ('pm4_shifts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_pm4_shifts', to='create.FinalPersonalShifts', verbose_name='pm4_shifts')),
                ('pm5_shifts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_pm5_shifts', to='create.FinalPersonalShifts', verbose_name='pm5_shifts')),
            ],
            options={
                'db_table': 'final_counter_shifts',
            },
        ),
        migrations.CreateModel(
            name='FinalAllShifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='year')),
                ('month', models.IntegerField(verbose_name='month')),
                ('day', models.IntegerField(verbose_name='day')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('counter_shifts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.FinalCounterShifts', verbose_name='counter_shifts')),
                ('kitchen_shifts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.FinalKitchenShifts', verbose_name='kitchen_shifts')),
                ('smg_shifts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.FinalSmgShifts', verbose_name='smg_shifts')),
            ],
            options={
                'db_table': 'final_all_shifts',
                'unique_together': {('year', 'month', 'day')},
            },
        ),
    ]
